#!/bin/bash
# Unit tests for setup-notifications.sh
# Tests the interactive setup wizard

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
RALPH_DIR="$(dirname "$SCRIPT_DIR")"
TEST_DIR="$SCRIPT_DIR/test-output-setup"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Test counters
TESTS_RUN=0
TESTS_PASSED=0
TESTS_FAILED=0

setup() {
    mkdir -p "$TEST_DIR"
    export HOME="$TEST_DIR"
}

teardown() {
    rm -rf "$TEST_DIR"
}

assert_equals() {
    local expected="$1"
    local actual="$2"
    local message="${3:-}"

    TESTS_RUN=$((TESTS_RUN + 1))
    if [ "$expected" = "$actual" ]; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "${GREEN}✓${NC} $message"
        return 0
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "${RED}✗${NC} $message"
        echo "  Expected: $expected"
        echo "  Actual:   $actual"
        return 1
    fi
}

assert_file_exists() {
    local file="$1"
    local message="${2:-File should exist}"

    TESTS_RUN=$((TESTS_RUN + 1))
    if [ -f "$file" ]; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "${GREEN}✓${NC} $message"
        return 0
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "${RED}✗${NC} $message"
        return 1
    fi
}

assert_contains() {
    local haystack="$1"
    local needle="$2"
    local message="${3:-}"

    TESTS_RUN=$((TESTS_RUN + 1))
    if echo "$haystack" | grep -q "$needle"; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "${GREEN}✓${NC} $message"
        return 0
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "${RED}✗${NC} $message"
        return 1
    fi
}

# ============================================
# CONFIG FILE CREATION TESTS
# ============================================

test_config_file_creation() {
    echo "Testing: Config file creation"

    local config="$TEST_DIR/.ralph.env"

    # Simulate config creation
    cat > "$config" << 'EOF'
# PortableRalph Configuration
# Generated by setup-notifications.sh on 2024-01-01

# Slack
export RALPH_SLACK_WEBHOOK_URL="https://hooks.slack.com/test"
EOF

    assert_file_exists "$config" "Config file should be created"

    local content
    content=$(cat "$config")
    assert_contains "$content" "RALPH_SLACK_WEBHOOK_URL" "Should contain Slack webhook"
}

test_config_file_permissions() {
    echo "Testing: Config file permissions (600)"

    local config="$TEST_DIR/.ralph.env"
    cat > "$config" << 'EOF'
export RALPH_SLACK_WEBHOOK_URL="test"
EOF
    chmod 600 "$config"

    local perms
    perms=$(stat -c "%a" "$config" 2>/dev/null || stat -f "%A" "$config" 2>/dev/null)
    assert_equals "600" "$perms" "Config file should have 600 permissions"
}

# ============================================
# SLACK CONFIGURATION TESTS
# ============================================

test_slack_webhook_saved() {
    echo "Testing: Slack webhook saved to config"

    local config="$TEST_DIR/.ralph.env"
    local webhook="https://hooks.slack.com/services/TEST/WEBHOOK/URL"

    cat > "$config" << EOF
# Slack
export RALPH_SLACK_WEBHOOK_URL="$webhook"
EOF

    local content
    content=$(cat "$config")
    assert_contains "$content" "$webhook" "Slack webhook should be saved"
}

# ============================================
# DISCORD CONFIGURATION TESTS
# ============================================

test_discord_webhook_saved() {
    echo "Testing: Discord webhook saved to config"

    local config="$TEST_DIR/.ralph.env"
    local webhook="https://discord.com/api/webhooks/TEST/WEBHOOK"

    cat > "$config" << EOF
# Discord
export RALPH_DISCORD_WEBHOOK_URL="$webhook"
EOF

    local content
    content=$(cat "$config")
    assert_contains "$content" "$webhook" "Discord webhook should be saved"
}

# ============================================
# TELEGRAM CONFIGURATION TESTS
# ============================================

test_telegram_credentials_saved() {
    echo "Testing: Telegram credentials saved to config"

    local config="$TEST_DIR/.ralph.env"
    local token="123456789:ABC-DEF1234567890"
    local chat_id="987654321"

    cat > "$config" << EOF
# Telegram
export RALPH_TELEGRAM_BOT_TOKEN="$token"
export RALPH_TELEGRAM_CHAT_ID="$chat_id"
EOF

    local content
    content=$(cat "$config")
    assert_contains "$content" "$token" "Telegram token should be saved"
    assert_contains "$content" "$chat_id" "Telegram chat ID should be saved"
}

# ============================================
# CUSTOM SCRIPT CONFIGURATION TESTS
# ============================================

test_custom_script_path_saved() {
    echo "Testing: Custom script path saved to config"

    local config="$TEST_DIR/.ralph.env"
    local script_path="/path/to/custom-notify.sh"

    cat > "$config" << EOF
# Custom Script
export RALPH_CUSTOM_NOTIFY_SCRIPT="$script_path"
EOF

    local content
    content=$(cat "$config")
    assert_contains "$content" "$script_path" "Custom script path should be saved"
}

test_custom_script_tilde_expansion() {
    echo "Testing: Tilde expansion in custom script path"

    local script_path="~/custom-notify.sh"
    local expanded="${script_path/#\~/$HOME}"

    assert_contains "$expanded" "$TEST_DIR" "Should expand tilde to HOME"
}

# ============================================
# MULTIPLE PLATFORMS TESTS
# ============================================

test_multiple_platforms_config() {
    echo "Testing: Multiple platforms in single config"

    local config="$TEST_DIR/.ralph.env"
    cat > "$config" << 'EOF'
# PortableRalph Configuration

# Slack
export RALPH_SLACK_WEBHOOK_URL="https://hooks.slack.com/test"

# Discord
export RALPH_DISCORD_WEBHOOK_URL="https://discord.com/api/webhooks/test"

# Telegram
export RALPH_TELEGRAM_BOT_TOKEN="123:ABC"
export RALPH_TELEGRAM_CHAT_ID="123"
EOF

    local content
    content=$(cat "$config")
    assert_contains "$content" "RALPH_SLACK_WEBHOOK_URL" "Should contain Slack"
    assert_contains "$content" "RALPH_DISCORD_WEBHOOK_URL" "Should contain Discord"
    assert_contains "$content" "RALPH_TELEGRAM_BOT_TOKEN" "Should contain Telegram"
}

# ============================================
# EXISTING CONFIG HANDLING TESTS
# ============================================

test_existing_config_detected() {
    echo "Testing: Existing config file detection"

    local config="$TEST_DIR/.ralph.env"
    echo "# Existing config" > "$config"

    assert_file_exists "$config" "Should detect existing config"
}

test_config_backup_on_reconfigure() {
    echo "Testing: Config backup when reconfiguring"

    local config="$TEST_DIR/.ralph.env"
    local backup="$TEST_DIR/.ralph.env.backup"

    echo "# Old config" > "$config"
    cp "$config" "$backup"

    assert_file_exists "$backup" "Should create backup of old config"
}

# ============================================
# INPUT VALIDATION TESTS
# ============================================

test_empty_webhook_skipped() {
    echo "Testing: Empty webhook URL should skip platform"

    local config="$TEST_DIR/.ralph.env"
    cat > "$config" << 'EOF'
# PortableRalph Configuration
# Generated by setup-notifications.sh

EOF

    # If user pressed Enter without providing webhook, config should be minimal
    local content
    content=$(cat "$config")

    # Should not contain webhook if empty
    TESTS_RUN=$((TESTS_RUN + 1))
    if ! echo "$content" | grep -q "RALPH_SLACK_WEBHOOK_URL"; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "${GREEN}✓${NC} Empty webhook should not be saved"
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "${RED}✗${NC} Empty webhook should not be saved"
    fi
}

test_webhook_url_format_validation() {
    echo "Testing: Webhook URL format validation concept"

    # Setup should ideally validate URLs
    # Testing the concept exists
    local valid_slack="https://hooks.slack.com/services/T/B/X"
    local valid_discord="https://discord.com/api/webhooks/ID/TOKEN"

    assert_contains "$valid_slack" "hooks.slack.com" "Slack URL should have correct domain"
    assert_contains "$valid_discord" "discord.com/api/webhooks" "Discord URL should have correct path"
}

# ============================================
# SCRIPT EXECUTABLE CHECK TESTS
# ============================================

test_custom_script_executable_check() {
    echo "Testing: Custom script executable check"

    local script="$TEST_DIR/test-notify.sh"
    echo "#!/bin/bash" > "$script"
    chmod -x "$script"  # Make non-executable

    TESTS_RUN=$((TESTS_RUN + 1))
    if [ ! -x "$script" ]; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "${GREEN}✓${NC} Should detect non-executable script"
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "${RED}✗${NC} Should detect non-executable script"
    fi
}

test_custom_script_make_executable() {
    echo "Testing: Make custom script executable"

    local script="$TEST_DIR/test-notify.sh"
    echo "#!/bin/bash" > "$script"
    chmod +x "$script"

    TESTS_RUN=$((TESTS_RUN + 1))
    if [ -x "$script" ]; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "${GREEN}✓${NC} Should make script executable"
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "${RED}✗${NC} Should make script executable"
    fi
}

# ============================================
# SOURCE VERIFICATION TESTS
# ============================================

test_config_can_be_sourced() {
    echo "Testing: Config file can be sourced"

    local config="$TEST_DIR/.ralph.env"
    cat > "$config" << 'EOF'
# PortableRalph Configuration
export RALPH_SLACK_WEBHOOK_URL="https://hooks.slack.com/test"
export RALPH_AUTO_COMMIT="true"
EOF

    # Try sourcing it
    local exit_code=0
    (source "$config") || exit_code=$?

    assert_equals 0 "$exit_code" "Config should be sourceable without errors"
}

test_config_syntax_validation() {
    echo "Testing: Config syntax validation"

    local config="$TEST_DIR/.ralph.env"
    cat > "$config" << 'EOF'
# Valid config
export RALPH_SLACK_WEBHOOK_URL="test"
EOF

    # Validate syntax
    local exit_code=0
    bash -n "$config" 2>/dev/null || exit_code=$?

    assert_equals 0 "$exit_code" "Config should have valid bash syntax"
}

# ============================================
# RUN ALL TESTS
# ============================================

run_all_tests() {
    echo "======================================"
    echo "Setup-Notifications.sh Unit Tests"
    echo "======================================"
    echo ""

    setup

    # Config file creation
    test_config_file_creation
    test_config_file_permissions

    # Platform configurations
    test_slack_webhook_saved
    test_discord_webhook_saved
    test_telegram_credentials_saved
    test_custom_script_path_saved
    test_custom_script_tilde_expansion

    # Multiple platforms
    test_multiple_platforms_config

    # Existing config handling
    test_existing_config_detected
    test_config_backup_on_reconfigure

    # Input validation
    test_empty_webhook_skipped
    test_webhook_url_format_validation

    # Script executable checks
    test_custom_script_executable_check
    test_custom_script_make_executable

    # Source verification
    test_config_can_be_sourced
    test_config_syntax_validation

    teardown

    # Print summary
    echo ""
    echo "======================================"
    echo "Test Summary"
    echo "======================================"
    echo "Tests run:    $TESTS_RUN"
    echo -e "Tests passed: ${GREEN}$TESTS_PASSED${NC}"
    echo -e "Tests failed: ${RED}$TESTS_FAILED${NC}"
    echo ""

    if [ $TESTS_FAILED -eq 0 ]; then
        echo -e "${GREEN}All tests passed!${NC}"
        return 0
    else
        echo -e "${RED}Some tests failed.${NC}"
        return 1
    fi
}

# Run tests
if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    run_all_tests
fi
